import { Member, Project, AIModel, ResearchService, ResearchNewsItem } from "./types";

export const members: Member[] = [
  {
    id: "anna",
    name: "Anna A.",
    initials: "AA",
    role: "Dev Lead",
    title: "Full-Stack / UI",
    color: "#3b82f6",
    status: "online",
    projects: ["fuji-2024", "viz-v3", "retail-heatmap"],
  },
  {
    id: "bolod",
    name: "Bolod O.",
    initials: "BO",
    role: "Analyst",
    title: "Data Analyst",
    color: "#22c55e",
    status: "online",
    projects: ["fuji-2024", "media-mix"],
  },
  {
    id: "tsend",
    name: "Tsend T.",
    initials: "ЦТ",
    role: "PM",
    title: "Project Manager",
    color: "#a855f7",
    status: "online",
    projects: ["fuji-2024", "retail-heatmap", "ad-q4"],
  },
  {
    id: "dorj",
    name: "Dorj B.",
    initials: "ДБ",
    role: "Backend Dev",
    title: "Backend Developer",
    color: "#f97316",
    status: "away",
    projects: ["viz-v3", "ad-q4"],
  },
  {
    id: "nara",
    name: "Nara E.",
    initials: "НЭ",
    role: "Data Engineer",
    title: "Data Engineer",
    color: "#6b7280",
    status: "offline",
    projects: ["media-mix"],
  },
];

export const projects: Project[] = [
  {
    id: "fuji-2024",
    title: "FUJI 2024 Research",
    subtitle: "Japan consumer market · Dentsu Japan partnership",
    status: "active",
    priority: "urgent",
    progress: 72,
    startDate: "2024-09-01",
    endDate: "2024-12-31",
    client: "Dentsu Japan",
    category: "Market Research",
    pm: "Tsend T.",
    members: [members[0], members[1], members[2]],
    tasks: [
      { id: "t1", title: "Survey design & approval", assignee: "Anna", status: "done", completed: true },
      { id: "t2", title: "Data collection Phase 1", assignee: "Bolod", status: "done", completed: true },
      { id: "t3", title: "Dashboard prototype", assignee: "Anna", status: "done", completed: true },
      { id: "t4", title: "Data analysis & visualization", assignee: "Anna, Bolod", status: "in-progress", completed: false },
      { id: "t5", title: "Client report draft", assignee: "Tsend", status: "pending", completed: false },
      { id: "t6", title: "Final presentation deck", assignee: "Anna", status: "pending", completed: false },
      { id: "t7", title: "Japan team review & sign-off", assignee: "Tsend", status: "low", completed: false },
    ],
    files: [
      { id: "f1", name: "FUJI2024_RawData_v3.xlsx", type: "xlsx", size: "4.2 MB", uploadedBy: "Bolod", uploadedAt: "3 days ago" },
      { id: "f2", name: "Survey_Analysis_Q3.xlsx", type: "xlsx", size: "1.8 MB", uploadedBy: "Anna", uploadedAt: "5 days ago" },
      { id: "f3", name: "Client_Presentation_Draft.pptx", type: "pptx", size: "6.1 MB", uploadedBy: "Tsend", uploadedAt: "1 week ago" },
      { id: "f4", name: "Research_Brief_FUJI2024.docx", type: "docx", size: "312 KB", uploadedBy: "Tsend", uploadedAt: "2 months ago" },
      { id: "f5", name: "Japan_Market_Overview_2024.pdf", type: "pdf", size: "2.4 MB", uploadedBy: "Bolod", uploadedAt: "3 months ago" },
      { id: "f6", name: "Figma — Dashboard Design", type: "link", size: "", uploadedBy: "Anna", uploadedAt: "2 weeks ago" },
    ],
  },
  {
    id: "viz-v3",
    title: "Viz Platform v3",
    subtitle: "Vue migration · Internal tooling",
    status: "review",
    priority: "high",
    progress: 45,
    startDate: "2024-08-01",
    endDate: "2025-02-28",
    client: "Internal",
    category: "Platform Development",
    pm: "Anna A.",
    members: [members[0], members[3]],
    tasks: [
      { id: "t1", title: "Architecture planning", assignee: "Anna", status: "done", completed: true },
      { id: "t2", title: "Vue 3 migration", assignee: "Dorj", status: "done", completed: true },
      { id: "t3", title: "Component library setup", assignee: "Anna", status: "in-progress", completed: false },
      { id: "t4", title: "API integration layer", assignee: "Dorj", status: "in-progress", completed: false },
      { id: "t5", title: "Testing & QA", assignee: "Anna, Dorj", status: "pending", completed: false },
      { id: "t6", title: "Deployment & documentation", assignee: "Dorj", status: "pending", completed: false },
    ],
    files: [
      { id: "f1", name: "Viz_v3_Architecture.docx", type: "docx", size: "890 KB", uploadedBy: "Anna", uploadedAt: "1 month ago" },
      { id: "f2", name: "Migration_Plan_v2.xlsx", type: "xlsx", size: "256 KB", uploadedBy: "Dorj", uploadedAt: "2 months ago" },
    ],
  },
  {
    id: "media-mix",
    title: "Media Mix Model",
    subtitle: "Python pipeline · Statistical modeling",
    status: "active",
    priority: "high",
    progress: 90,
    startDate: "2024-06-01",
    endDate: "2024-11-30",
    client: "Internal",
    category: "Data Science",
    pm: "Tsend T.",
    members: [members[1], members[4]],
    tasks: [
      { id: "t1", title: "Data pipeline design", assignee: "Nara", status: "done", completed: true },
      { id: "t2", title: "Model training v1", assignee: "Bolod", status: "done", completed: true },
      { id: "t3", title: "Validation & testing", assignee: "Bolod, Nara", status: "done", completed: true },
      { id: "t4", title: "Final model tuning", assignee: "Bolod", status: "in-progress", completed: false },
      { id: "t5", title: "Report generation", assignee: "Nara", status: "pending", completed: false },
    ],
    files: [
      { id: "f1", name: "MediaMix_Pipeline_v2.py", type: "docx", size: "45 KB", uploadedBy: "Nara", uploadedAt: "1 week ago" },
    ],
  },
  {
    id: "retail-heatmap",
    title: "Retail Heatmap Tool",
    subtitle: "Geo-analytics · Location intelligence",
    status: "planned",
    priority: "medium",
    progress: 20,
    startDate: "2025-01-01",
    endDate: "2025-06-30",
    client: "Internal",
    category: "Analytics Tools",
    pm: "Tsend T.",
    members: [members[0], members[2]],
    tasks: [
      { id: "t1", title: "Requirements gathering", assignee: "Tsend", status: "done", completed: true },
      { id: "t2", title: "Tech stack selection", assignee: "Anna", status: "in-progress", completed: false },
      { id: "t3", title: "Prototype development", assignee: "Anna", status: "pending", completed: false },
      { id: "t4", title: "Geo data integration", assignee: "Anna", status: "pending", completed: false },
    ],
    files: [],
  },
  {
    id: "ad-q4",
    title: "Ad Effectiveness Q4",
    subtitle: "Campaign analysis · Performance metrics",
    status: "active",
    priority: "high",
    progress: 60,
    startDate: "2024-10-01",
    endDate: "2025-01-31",
    client: "Dentsu Japan",
    category: "Campaign Analysis",
    pm: "Tsend T.",
    members: [members[2], members[3]],
    tasks: [
      { id: "t1", title: "Data collection", assignee: "Dorj", status: "done", completed: true },
      { id: "t2", title: "Attribution modeling", assignee: "Dorj", status: "done", completed: true },
      { id: "t3", title: "Performance dashboard", assignee: "Dorj", status: "in-progress", completed: false },
      { id: "t4", title: "Client presentation", assignee: "Tsend", status: "pending", completed: false },
    ],
    files: [
      { id: "f1", name: "AdEffectiveness_Q4_Data.xlsx", type: "xlsx", size: "3.1 MB", uploadedBy: "Dorj", uploadedAt: "2 days ago" },
    ],
  },
];

export const aiModels: AIModel[] = [
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    description: "Advanced reasoning model with strong analytical capabilities, extended thinking, and multimodal understanding. Powers most production AI applications.",
    releaseDate: "2025-02",
    capabilities: ["Text generation", "Code", "Analysis", "Vision", "Tool use", "Extended thinking"],
    contextWindow: "200K tokens",
    status: "available",
    tags: ["Anthropic", "Reasoning", "Multimodal"],
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    description: "OpenAI's flagship multimodal model with real-time audio, vision, and text capabilities. Strong at structured outputs and function calling.",
    releaseDate: "2024-05",
    capabilities: ["Text", "Vision", "Audio", "Code", "Tool use"],
    contextWindow: "128K tokens",
    status: "available",
    tags: ["OpenAI", "Multimodal", "Real-time"],
  },
  {
    id: "gemini-2-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    description: "Google's next-gen multimodal model with native image generation and real-time streaming. Supports the largest context window available.",
    releaseDate: "2025-01",
    capabilities: ["Text", "Vision", "Audio", "Image gen", "Code"],
    contextWindow: "1M tokens",
    status: "available",
    tags: ["Google", "Multimodal", "Long context"],
  },
  {
    id: "deepseek-r2",
    name: "DeepSeek R2",
    provider: "DeepSeek",
    description: "Open-source reasoning model rivaling frontier models at significantly lower cost. Excels at mathematics, science, and complex logical reasoning.",
    releaseDate: "2025-03",
    capabilities: ["Reasoning", "Math", "Code", "Science"],
    contextWindow: "128K tokens",
    status: "available",
    tags: ["Open-source", "Reasoning", "Efficient"],
  },
  {
    id: "llama-4",
    name: "Llama 4",
    provider: "Meta",
    description: "Meta's open-weight frontier model with multimodal capabilities and mixture-of-experts architecture for highly efficient inference.",
    releaseDate: "2025-04",
    capabilities: ["Text", "Vision", "Code", "Multilingual"],
    contextWindow: "256K tokens",
    status: "available",
    tags: ["Meta", "Open-weight", "MoE"],
  },
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xAI",
    description: "xAI's advanced reasoning model with real-time web access and deep thinking mode. Strong at STEM tasks and up-to-date knowledge.",
    releaseDate: "2025-02",
    capabilities: ["Reasoning", "Web search", "Math", "Code"],
    contextWindow: "128K tokens",
    status: "available",
    tags: ["xAI", "Real-time", "Reasoning"],
  },
];

export const researchServices: ResearchService[] = [
  {
    id: "anthropic-api",
    name: "Anthropic API",
    type: "AI API",
    description: "Access Claude models via REST API. Supports tool use, vision, streaming, prompt caching, and extended thinking for complex workflows.",
    provider: "Anthropic",
    status: "active",
    tags: ["API", "Claude", "Production"],
  },
  {
    id: "openai-api",
    name: "OpenAI API",
    type: "AI API",
    description: "Access GPT-4, DALL-E, Whisper, and Embeddings. Includes Assistants API and fine-tuning endpoints for custom model adaptation.",
    provider: "OpenAI",
    status: "active",
    tags: ["API", "GPT-4", "DALL-E"],
  },
  {
    id: "vertex-ai",
    name: "Vertex AI",
    type: "ML Platform",
    description: "Google Cloud's managed ML platform with Gemini models, AutoML, and comprehensive MLOps tooling for end-to-end model lifecycle.",
    provider: "Google Cloud",
    status: "active",
    tags: ["GCP", "Gemini", "MLOps"],
  },
  {
    id: "hugging-face",
    name: "Hugging Face Hub",
    type: "Model Registry",
    description: "Open-source model hub with 500K+ models, datasets, and Spaces. Primary registry for open-weight models and community research.",
    provider: "Hugging Face",
    status: "active",
    tags: ["Open-source", "Models", "Datasets"],
  },
  {
    id: "langchain",
    name: "LangChain",
    type: "Framework",
    description: "Framework for building LLM-powered applications with chains, agents, and retrieval systems. Large ecosystem with 100+ integrations.",
    provider: "LangChain Inc.",
    status: "active",
    tags: ["Framework", "Agents", "RAG"],
  },
  {
    id: "supabase-pgvector",
    name: "Supabase + pgvector",
    type: "Vector Database",
    description: "PostgreSQL-based vector storage for semantic search and RAG applications. Combines relational and vector queries in one database.",
    provider: "Supabase",
    status: "active",
    tags: ["Vector DB", "PostgreSQL", "RAG"],
  },
];

export const researchNews: ResearchNewsItem[] = [
  {
    id: "n1",
    title: "Claude 4 Series Released with Extended Thinking",
    summary: "Anthropic releases Claude Opus 4, Sonnet 4, and Haiku 4 with enhanced reasoning, 200K context, and improved multimodal capabilities across all tiers.",
    source: "Anthropic Blog",
    date: "2025-04-15",
    tags: ["Anthropic", "Claude 4", "LLM"],
  },
  {
    id: "n2",
    title: "Google Gemini 2.0 Flash Achieves 1M Token Context",
    summary: "Gemini 2.0 Flash supports 1M token context window with native image generation and real-time voice — the largest context of any production model.",
    source: "Google AI Blog",
    date: "2025-03-28",
    tags: ["Google", "Gemini", "Long Context"],
  },
  {
    id: "n3",
    title: "Meta Releases Llama 4 with MoE Architecture",
    summary: "Llama 4 Scout and Maverick use mixture-of-experts architecture, delivering frontier performance with fully open weights for self-hosted deployments.",
    source: "Meta AI",
    date: "2025-04-05",
    tags: ["Meta", "Llama 4", "Open-source"],
  },
  {
    id: "n4",
    title: "RAG vs Fine-tuning: 2025 Best Practices",
    summary: "New research shows RAG outperforms fine-tuning for domain adaptation in 85% of enterprise use cases when combined with cross-encoder reranking.",
    source: "arXiv",
    date: "2025-04-10",
    tags: ["RAG", "Fine-tuning", "Research"],
  },
  {
    id: "n5",
    title: "AI Agents Go Mainstream in Enterprise 2025",
    summary: "Survey of 500 enterprises shows 67% now deploy autonomous AI agents, up from 12% in 2024, with data analysis and code generation leading use cases.",
    source: "McKinsey & Co.",
    date: "2025-04-20",
    tags: ["Agents", "Enterprise", "Trends"],
  },
];

export const dashboardStats = {
  totalProjects: 12,
  newThisMonth: 3,
  inProgress: 7,
  urgent: 2,
  members: 24,
  teams: 5,
  documents: 148,
  docsThisWeek: 16,
};
